travis:
  secure:
    BINSTAR_TOKEN: St3yrtwhIavpcKQN+JAJUiCG9FZSrxaQwfEROqQ8JSLoJvXAPJwjaFNlsQCF5oMlk2HOjnEw3Vf8lHofR/5TLrZ3VgJ+cCiGQ6S90qllto6JKQX2HVp400RswwddS/F+Y1w7BX9mk+3A8TxFkqdjZA8gCOhN52Iix7Sq60cMN+Sv4FHhnZjHAgNbmCsUUNZQQ0KHPU4dvR/g2R+nyPlv7JnuIh5R0ZnprNFDUnlozd8l2UrY3regOD0jxs/6hJyikoLi2yFzenc8jQN9U1ZJUc6J6uNZpGM6PQ6fct16/Waw6TS9fcu8m4smVQ7llLMOCQfaNv35J9+gZ8opnAi1KYShL13oeKuzD2n268teO1+1yu/hA/7xX9pIs0/Bo8/ntcfQTK6YSxJTQbRUUuTCeMS7LVbP86fjvqHjSbe1F9PmXDOB0HA4otzSeyHac+TJfpu668lQ7ST3v5Q4MuYhoCV6fZX8YkP7oTdAZZBWbpjS1GaB1blj2Enh3gLGxVBECZKPKldmpXnSBHWbR2EDWQDJ7lDexUJmnifKCrp6K0IUjiYxXcZBVcqme6VKk3YevGk+MbnZb7Dc8c4+UQVH0/ijjMLNFiIMYhfF6Kvqwq+q+ID0dy8Kq93dOGK8DO2zqbLeAm5XPh0shOGaDguTuMSmBnjeHYfOIEc4TpevpE8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
