travis:
  secure:
    BINSTAR_TOKEN: iaTYoZx0UMjA7/gTQPPGRWiAtHVgdXI4HuLMdyb1ta8jTyUJG1BmAqwju3aA773/9myN6fX71VVely8pXUSCqNiEsr9BGR4oAiY1eB7UViaYD6h9EKy0373+bbRMnypKeEtub9N5bKRKKYCgpPAXz/4G/gJN2EoJtjp13NVn7amwXrXSec+Hv+OF+JC6WdVZkEhJ+tijzghteAXLu30bZwpxhAFfChK4D7KCnoBwlVnxFwZjZ7lX7UZV0R2YdJMfk+ucrSAEaJNuRkeH5Kq61Gvl3QAqVDN0o9zZZDdbitwe2dehXP8+1O2ra3gLlearbzjozAzg+ebE6F1fjpavM5mCVeMlYdcmhvACAe8ILfL7pI7iGjBLjJd6ywYYboZSPXNtbM6MduNJyUPQLEMrR78lb40y7m33Ho9+6YaDCXx3ZYop24A3nNrzC9STh5mXhmCrPNMjZa3J4oa0EQtcBGM7DVmGZTNFqk/E5DKU8m+YC3V8Oo7S7Slo72n0c2VAjbZEtQ8HYXc35eLL6+vi2ZxZxeEQEfQ/UuSGLKvg5nNqMBhIVII4ykoILg81D7h1TKdRxXV2BI2HDjKJsT9LAkkCGJJrJ06aG+eo9mzUBI4jzdmT2IYyXTXamHt/pCIVWsRzrnGL5DnPME7rxt4R+iyy086fUmkXwAX5eg5j1RE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
